### ISSUE TITLE
Toast Alignment

### ISSUE THREAD

**Issue by Akitha** [dreyliky/angular-bootstrap-toasts#1]
I think alignment function is missing in the current release 
So is there any way to do positioning in the toasts

Or any way to control Container Settings

**Comment by dreyliky** [comment]
Hello. You can control container settings by passing input parameters.
For toasts alignment, please use property **Placement** of container component.

For example
`[Placement]="{ position: 'topLeft' }"`

Available options:
`type PositionType = 'topLeft' | 'topRight' | 'bottomLeft' | 'bottomRight';`

You can also add margin for container, passing property in **Placement** object:
```
marginLeft?: string;
marginRight?: string;
marginTop?: string;
marginBottom?: string;
```

You can check an example here (section "Container Settings"): [Demo](https://dreyliky.github.io/angular-bootstrap-toasts-demo)
